POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikhhbm5hIiwiaWQiOiI2YTE4MmMyYmU1ZmVmNzk2OGUwYWEyMGUiLCJpYXQiOjE3ODAwNDYyNDIsImV4cCI6MTc4MDA0OTg0Mn0.rcMERjSgmVHcnkY8vv4VcCy1TrzrI_3kI_1rdElXBfI

{
  "title": "Marjan MuotiBlogi",
  "author": "Vogue",
  "url": "www.vogue.com",
  "likes": 10
}